package `in`.shvms.trackme.theme

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import kotlin.math.pow

/**
 * Every ramp entry sits at the tone its name claims.
 *
 * ### Why this replaces "regenerate with Material Color Utilities"
 *
 * The ramps were generated by holding hue and chroma in CIELCh and sweeping L*, where Material's
 * own generator uses CAM16-based HCT. That difference was recorded as an open caveat for most of
 * 1.8.0 — but it is narrower than it sounds, because **HCT's tone *is* CIELAB L***. The two
 * systems differ in how they model hue and chroma, not tone. So the tone axis, which is the axis
 * the entire design system indexes on, is not an approximation at all — and this test measures it
 * rather than asserting it.
 *
 * What genuinely remains approximate is chroma in the 70–90 band, where gamut mapping bites: a
 * CAM16 chroma of 48 and a CIELCh chroma of 48 are not the same quantity. That shows up as the
 * primary ramp desaturating slightly earlier than Material's would. It is a difference in
 * saturation, not in lightness, and every contrast pair the app actually renders is measured
 * empirically by [ThemeContrastTest] — which is the property that matters and does not care which
 * colour space produced the value.
 *
 * Reads the source rather than the compiled object because `Color` is a value class over `ULong`,
 * so reflecting over the ramp gets you `long` getters and no tone names — and because reading the
 * source covers any entry someone adds later without touching this file.
 */
class TonalRampAccuracyTest {

    /**
     * sRGB quantisation alone moves L* by up to about 0.2 in the midtones, so anything inside half
     * a tone point is exact for every purpose the palette is used for. Observed worst case across
     * all 80 entries is 0.21.
     */
    private val toleranceLStar = 0.5

    private val entry = Regex("""val ([A-Za-z]+?)(\d+) = Color\(0xFF([0-9A-Fa-f]{6})\)""")

    @Test
    fun `every ramp entry sits at its nominal tone`() {
        val entries = parseRamps()
        assertTrue(
            "No ramp entries parsed — the palette format changed and this test is now vacuous",
            entries.size >= 60,
        )

        val drifted = entries
            .map { it to (lStar(it.hex) - it.tone) }
            .filter { (_, delta) -> kotlin.math.abs(delta) > toleranceLStar }
            .map { (e, delta) -> "${e.ramp}${e.tone} is L*${"%.2f".format(lStar(e.hex))} (${"%+.2f".format(delta)})" }

        assertTrue(
            "These ramp values do not sit at the tone their name claims, so anything reasoning " +
                "about tone distance — contrast headroom, container pairing, dark-theme " +
                "inversion — is reasoning about the wrong number:\n" + drifted.joinToString("\n"),
            drifted.isEmpty(),
        )
    }

    @Test
    fun `each ramp increases monotonically in lightness`() {
        // Ordering is what makes a ramp a ramp. A single inverted pair silently breaks every
        // "one step lighter" decision in the scheme, and would not show up as a contrast failure.
        for ((ramp, entries) in parseRamps().groupBy { it.ramp }) {
            val sorted = entries.sortedBy { it.tone }
            for ((lower, higher) in sorted.zipWithNext()) {
                assertTrue(
                    "$ramp${higher.tone} (L*${"%.2f".format(lStar(higher.hex))}) is not lighter " +
                        "than $ramp${lower.tone} (L*${"%.2f".format(lStar(lower.hex))})",
                    lStar(higher.hex) > lStar(lower.hex),
                )
            }
        }
    }

    private data class RampEntry(val ramp: String, val tone: Int, val hex: String)

    private fun parseRamps(): List<RampEntry> =
        entry.findAll(paletteSource()).map { m ->
            RampEntry(m.groupValues[1], m.groupValues[2].toInt(), m.groupValues[3])
        }.toList()

    /** CIELAB L* of an sRGB hex — identical to HCT tone, which is the whole point of this test. */
    private fun lStar(hex: String): Double {
        fun linear(channel: Int): Double {
            val c = channel / 255.0
            return if (c <= 0.04045) c / 12.92 else ((c + 0.055) / 1.055).pow(2.4)
        }

        val r = linear(hex.substring(0, 2).toInt(16))
        val g = linear(hex.substring(2, 4).toInt(16))
        val b = linear(hex.substring(4, 6).toInt(16))

        // Y under D65, then the CIE lightness transfer.
        val y = 0.2126729 * r + 0.7151522 * g + 0.0721750 * b
        val f = if (y > 0.008856) y.pow(1.0 / 3.0) else 7.787 * y + 16.0 / 116.0
        return 116.0 * f - 16.0
    }

    private fun paletteSource(): String {
        var dir: File? = File("").absoluteFile
        val rel = "app/src/main/java/in/shvms/trackme/theme/TrackMeTonalPalette.kt"
        while (dir != null) {
            File(dir, rel).takeIf { it.exists() }?.let { return it.readText() }
            File(dir, rel.removePrefix("app/")).takeIf { it.exists() }?.let { return it.readText() }
            dir = dir.parentFile
        }
        throw AssertionError("TrackMeTonalPalette.kt not found")
    }
}
